# Generated by Django 4.0.2 on 2022-02-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='info',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='number',
            new_name='price',
        ),
    ]
