# Generated by Django 4.0.2 on 2022-02-12 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digi', '0002_basket_delete_info_rename_number_product_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='sale',
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
