# Generated by Django 4.0.2 on 2022-02-13 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0003_rename_product_sale_basket_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sale',
            new_name='product',
        ),
    ]
