# Generated by Django 4.0.2 on 2022-02-13 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0005_basket_metal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='user',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='basket',
        ),
    ]
