# Generated by Django 4.0.2 on 2022-02-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0010_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
